// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0jYJ2QMiHXoxm1ESnqfyNPASnnG9Ik8',
    appId: '1:913124981780:web:1229e36c87f4b36b007b01',
    messagingSenderId: '913124981780',
    projectId: 'blockchain-based-major-project',
    authDomain: 'blockchain-based-major-project.firebaseapp.com',
    storageBucket: 'blockchain-based-major-project.firebasestorage.app',
    measurementId: 'G-3L6CK8HSWZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Qa4WbvHnKTpKrrkr3ltjIFU70pmDPbw',
    appId: '1:913124981780:ios:b2913e4ac815e20b007b01',
    messagingSenderId: '913124981780',
    projectId: 'blockchain-based-major-project',
    storageBucket: 'blockchain-based-major-project.firebasestorage.app',
    iosClientId: '913124981780-sin1v5mpova5ek1lpqm1268jrrhahvpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Qa4WbvHnKTpKrrkr3ltjIFU70pmDPbw',
    appId: '1:913124981780:ios:b2913e4ac815e20b007b01',
    messagingSenderId: '913124981780',
    projectId: 'blockchain-based-major-project',
    storageBucket: 'blockchain-based-major-project.firebasestorage.app',
    iosClientId: '913124981780-sin1v5mpova5ek1lpqm1268jrrhahvpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCUuj3W1UGz6Wt3pmlGcl2Gg_OlbaKdpE',
    appId: '1:913124981780:android:7e50342da0d24199007b01',
    messagingSenderId: '913124981780',
    projectId: 'blockchain-based-major-project',
    storageBucket: 'blockchain-based-major-project.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0jYJ2QMiHXoxm1ESnqfyNPASnnG9Ik8',
    appId: '1:913124981780:web:0dc45a5d959941b6007b01',
    messagingSenderId: '913124981780',
    projectId: 'blockchain-based-major-project',
    authDomain: 'blockchain-based-major-project.firebaseapp.com',
    storageBucket: 'blockchain-based-major-project.firebasestorage.app',
    measurementId: 'G-DGKQ9KP9YY',
  );

}