import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'pages/auth_page.dart';
// ignore: uri_does_not_exist
import 'firebase_options.dart'; // This file is generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  // If you haven't generated firebase_options.dart yet, you can use:
  // await Firebase.initializeApp(); 
  // But for better platform support, use:
  try {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
      // Fallback if options file is not yet generated or properly configured
      // valid for standard android/ios setups sometimes if google-services.json is present
      // but flutterfire configure is recommended.
      print("Firebase initialization failed/warning: $e. Make sure to run 'flutterfire configure'");
      // We might try to continue just for UI testing if firebase features aren't immediately accessed
      // but Auth will fail. 
  }

  runApp(const BlockchainDocumentApp());
}

class BlockchainDocumentApp extends StatelessWidget {
  const BlockchainDocumentApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Blockchain Document Verification',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.blue,
          primary: Colors.blue[700],
          secondary: Colors.blue[900],
        ),
        useMaterial3: true,
        fontFamily: 'Roboto', // Optional: Ensure you have fonts or remove
      ),
      home: const AuthPage(),
      debugShowCheckedModeBanner: false,
    );
  }
}
